apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: my-certificate
spec:
  issuerRef: 
    name: selfsigned-issuer
    kind: ClusterIssuer
  secretName: tls-mycert.io
  commonName: cert-mycert.io
  dnsNames: 
    - test-cert.io
